#!/bin/bash
export COLOUR_AQUA="§b"
export COLOUR_GREEN_DARK="§2"
export COLOUR_ORANGE="§6"
export COLOUR_RED="§c"
export COLOUR_YELLOW="§e"

export COLOUR_BOLD="§l"
export COLOUR_RESET="§r"

export COLOUR_TEXT_DENIED="${COLOUR_RED}${COLOUR_BOLD}"
export COLOUR_TEXT_MENTION_PLAYER="${COLOUR_GREEN_DARK}"
export COLOUR_TEXT_MENTION_REGION="${COLOUR_YELLOW}"
export COLOUR_TEXT_MENTION_SUBREGION="${COLOUR_AQUA}"
export COLOUR_TEXT_MESSAGE="${COLOUR_ORANGE}"
export COLOUR_TEXT_MESSAGE_PUBLIC="${COLOUR_YELLOW}"
