#!/bin/bash
export COLOUR_AQUA="§b"
export COLOUR_ORANGE="§6"
export COLOUR_RED="§c"

export COLOUR_BOLD="§l"

export COLOUR_TEXT_DENIED="${COLOUR_RED}${COLOUR_BOLD}"
export COLOUR_TEXT_MENTION_PLAYER="${COLOUR_AQUA}"
export COLOUR_TEXT_MENTION_REGION="${COLOUR_TEXT_MENTION_PLAYER}"
export COLOUR_TEXT_MESSAGE="${COLOUR_ORANGE}"
