#!/bin/bash
export COLOUR_AQUA="§b"
export COLOUR_AQUA_HEX="#55FFFF"
export COLOUR_AQUA_XML="<aqua>"
export COLOUR_GREEN_DARK="§2"
export COLOUR_GREEN_DARK_XML="<dark_green>"
export COLOUR_GREEN_LIGHT="§a"
export COLOUR_GREEN_LIGHT_XML="<green>"
export COLOUR_ORANGE="§6"
export COLOUR_ORANGE_HEX="#FFAA00"
export COLOUR_ORANGE_XML="<gold>"
export COLOUR_PINK="§d"
export COLOUR_PURPLE_DARK="§5"
export COLOUR_PURPLE_DARK_XML="<dark_purple>"
export COLOUR_RED="§c"
export COLOUR_RED_XML="<red>"
export COLOUR_WHITE="§f"
export COLOUR_YELLOW="§e"
export COLOUR_YELLOW_XML="<yellow>"

export COLOUR_BOLD="§l"

export COLOUR_RESET="§r"
export COLOUR_RESET_XML="<reset>"

export COLOUR_ANNOUNCEMENT="${COLOUR_RESET}${COLOUR_PINK}"
export COLOUR_ACTION="${COLOUR_RESET}${COLOUR_YELLOW}"
export COLOUR_ACTION_XML="${COLOUR_RESET_XML}${COLOUR_YELLOW_XML}"

export COLOUR_HIGHLIGHT="${COLOUR_RESET}${COLOUR_AQUA}"
export COLOUR_HIGHLIGHT_HEX="${COLOUR_AQUA_HEX}"
export COLOUR_HIGHLIGHT_XML="${COLOUR_RESET_XML}${COLOUR_AQUA_XML}"

export COLOUR_MESSAGE="${COLOUR_RESET}${COLOUR_ORANGE}"
export COLOUR_MESSAGE_HEX="${COLOUR_ORANGE_HEX}"
export COLOUR_MESSAGE_XML="${COLOUR_RESET_XML}${COLOUR_ORANGE_XML}"

export COLOUR_CHAT="${COLOUR_RESET}${COLOUR_WHITE}"
export COLOUR_CHAT_PRIVATE="${COLOUR_RESET_XML}${COLOUR_GREEN_LIGHT}"

export COLOUR_ERROR="${COLOUR_RESET}${COLOUR_RED}"
export COLOUR_ERROR_XML="${COLOUR_RESET_XML}${COLOUR_RED_XML}"

export COLOUR_SUCCESS="${COLOUR_RESET}${COLOUR_GREEN_LIGHT}"
export COLOUR_SUCCESS_XML="${COLOUR_RESET_XML}${COLOUR_GREEN_LIGHT_XML}"

export COLOUR_ALERT="${COLOUR_ERROR}"

export COLOUR_DENIED="${COLOUR_ERROR}"

export COLOUR_COUNTRY="${COLOUR_YELLOW}"
export COLOUR_PLAYER="${COLOUR_GREEN_DARK}"
export COLOUR_PLAYER_XML="${COLOUR_GREEN_DARK_XML}"
export COLOUR_PLUGIN="${COLOUR_PURPLE_DARK}"
export COLOUR_PLUGIN_XML="${COLOUR_HIGHLIGHT_XML}"
export COLOUR_REGION="${COLOUR_YELLOW}"
export COLOUR_SETTLEMENT="${COLOUR_AQUA}"
export COLOUR_SUBREGION="${COLOUR_AQUA}"
